version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Congratulations" present in index.html file"
            - grep "Congratulations" index.html
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - index.html
        - appspec.yml
    discard-paths: yes

            
